### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_jayg_ppi2020#2]

**Comment by Andrexafk28** [comment]
![GitHub Logo](
![image](https://user-images.githubusercontent.com/66080104/86275457-efc04600-bb98-11ea-9b61-f42179ed8768.png)
)
Format: ![Alt Text](url)

**Comment by Andrexafk28** [comment]
![Presentación sin título](https://user-images.githubusercontent.com/66080104/86301145-b0125200-bbca-11ea-8b74-976dab64bb69.jpg)

**Comment by JohnFlorez25** [comment]
@Andrexafk28 @ShadowReco @owllwing El diagrama de espina de pescado debe estar orientado al problema a abordar en este caso "existe mucha desinformación sobre el  impacto en la salud de las bebidas energéticas" teniendo en cuenta esto, se identifican las causas de dicho problema , no se coloca en las causas los impactos en la salud de las personas que consumen bebidas energéticas.
