### ISSUE TITLE
Formular la Declaración de la Situación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_jayg_ppi2020#3]

**Comment by Andrexafk28** [comment]
![4TCXlGAN_400x400](https://user-images.githubusercontent.com/66080104/86317560-4f4c3f00-bbf5-11ea-9467-ec144bfc8c23.jpg)

**La desinformación en la que se ven involucradas una gran variedad personas frente al consumo de los energizantes es muy negativa ya que gracias esto las personas se pueden ver afectadas de distintas maneras ya que si las personas no son conscientes de los que están tomando pueden ser afectados por ciertos efectos como lo son adicción a los energizantes, también a ataques de ansiedad, problemas cardíacos, tics nerviosos, problemas de sueño, etc.**
