### ISSUE TITLE
Crear el Tablero de Visión del Producto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_jayg_ppi2020#5]

**Comment by Andrexafk28** [comment]
![Sin título](https://user-images.githubusercontent.com/66080104/86317849-15c80380-bbf6-11ea-98b6-f63132e2318a.png)

**Comment by JohnFlorez25** [comment]
@Andrexafk28 @ShadowReco @owllwing Mejor la descripción de la visión del producto, colocar cada uno de los interesados, mínimo deben ser tres interesados y como mínimo hay que identificar 3 necesidades, 3 características del producto y 3 beneficios.
